import { ClerkProvider } from "@clerk/nextjs"
import { Inter } from "next/font/google"
import "../globals.css"
import LeftSideBar from "@components/layout/LeftSideBar"
import MainContainer from "@components/layout/MainContainer"
import Topbar from "@components/layout/Topbar"
import RightSideBar from "@components/layout/RightSideBar"
import ButtonBar from "@components/layout/ButtonBar"
export const metadata = {
    title: 'Mis Media',
    description: 'Generated by Next.js'
}
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${inter.className} bg-purple-2`}>
                    <main className="flex flex-row">
                        <LeftSideBar />
                        <MainContainer>
                            {/* <Topbar /> */}
                            {children}
                        </MainContainer>
                        <RightSideBar />
                    </main>
                    <ButtonBar />
                </body>
            </html>
        </ClerkProvider>

    )
}